feat: add call-hierarchy
atom-community/atom-ide-outline pull request #131
Opened 2021-07-11 23:45 UTC by ayame113

This PR adds the functionality of the call hierarchy.

- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_prepareCallHierarchy
- https://code.visualstudio.com/updates/v1_43#_call-hierarchy-support-for-javascript-and-typescript

![image](https://user-images.githubusercontent.com/40050810/125212365-e3141900-e2e7-11eb-8b9d-091a4ae00df7.png)

Originally, this feature was implemented as a standalone package to support atom-ide-deno. (https://github.com/ayame113/call-hierarchy)
Since there are some overlaps in the implementation, I would like to move the implementation from there and add this feature to the outline package.

TODO:
- [ ] Add type definition to atom-ide-base
- [ ] Implement provider in atom-language client
- [ ] Move implementation from original package

2021-07-12 01:46 UTC, aminya requested changes
This is awesome. 🚀 

I haven't tried it yet, but I prefer that call hierarchy be a button like Reveal cursor, which clicking on it changes the outline to hierarchy. This would also allow using the search bar for it

2021-07-15 11:37 UTC, ayame113 commented
The commit history is terrible because I accidentally used an old branch. Excuse me.

For now, it works with atom-ide-deno 1.12.0 and this branch.

> I prefer that call hierarchy be a button like Reveal cursor, which clicking on it changes the outline to hierarchy.

Does that mean you want the call hierarchy to appear in the same tab as the outline? Currently, Outline and Call-Hierarchy are displayed in separate tabs. I prefer the current behavior. Reason:
- Each can be displayed side by side
- The internal structure of the outline and the call hierarchy is too different, which may interfere with future function additions.
-----
I made a video of the current behavior.
The information on the Call Hierarchy tab is updated as the cursor moves.

https://user-images.githubusercontent.com/40050810/125781090-81ee046e-ac20-4cbb-83c7-4b6c93e467b2.mp4

2021-07-16 01:24 UTC, ayame113 commented on package.json
>      "typescript": "^4.3.4"
Added dependencies according to build error message. I will remove it if there is a problem.

2021-07-16 01:27 UTC, ayame113 commented on src/call-hierarchy/statuses.ts
> +  },
It might be better to change the example of the IDE package, but I do not know the package that provides the call hierarchy.

2021-07-16 01:28 UTC, ayame113 commented on src/utils.ts
> +  // LSP specification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol
Moved functions referenced from both the outline and call hierarchy to utils.ts.

2021-07-16 01:34 UTC, ayame113 commented
The implementation is almost finished, so I'll add tests if there is no problem. Please comment if there is something you want to change.👍

2021-07-22 14:22 UTC, aminya commented
@ayame113 I merged [the atom-languageclient PR](https://github.com/atom-community/atom-languageclient/pull/172). This should make it easier for you to test things.

2021-07-22 17:06 UTC, aminya commented
> The commit history is terrible because I accidentally used an old branch. Excuse me.
> 
> For now, it works with atom-ide-deno 1.12.0 and this branch.
> 
> > I prefer that call hierarchy be a button like Reveal cursor, which clicking on it changes the outline to hierarchy.
> 
> Does that mean you want the call hierarchy to appear in the same tab as the outline? Currently, Outline and Call-Hierarchy are displayed in separate tabs. I prefer the current behavior. Reason:
> 
> * Each can be displayed side by side
> * The internal structure of the outline and the call hierarchy is too different, which may interfere with future function additions.
> 
> I made a video of the current behavior.
> The information on the Call Hierarchy tab is updated as the cursor moves.
> 
>  mod.ts.C__Users_azusa_tmp_deno_project.Atom.2021-07-15.20-29-09.mp4

Yeah, not adding another tab to Atom would make the UI less cluttered, and it will have better performance as only one of them will be updated at one moment. A button to switch between the two will fix this issue nicely.

2021-07-31 21:52 UTC, ayame113 commented
> I merged the atom-languageclient PR. This should make it easier for you to test things.

Thank you!

> P.S: Sorry about the close/open thing. That was a bug in our repository-sync script.

No problem👍

2021-07-31 21:54 UTC, ayame113 commented
Since the function has recursive calls, the display of the call hierarchy is also recursive. So we need to use a different search logic than outline.
Searching for function names asynchronously from deep dependencies (like node_modules) will slow down the search for the call hierarchy.

> We could optionally make it possible to open the call hierarchy in a separate tab, but by default, we should aim for a less cluttered UI.

I would like to implement it this way once. (We can open a PR that changes the UI later if needed)

2021-08-16 04:29 UTC, ayame113 commented
I tried to rebase and the operation failed, so I reopened the pull request #136. sorry.

2021-08-16 04:29 UTC, closed without merging